# Generated by Django 4.2.14 on 2024-08-12 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='can_take_from_pool',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='coin_per_tap',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='coin_pool',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='level_xp',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='7MKKqnaKJeE1Bvu7', max_length=30),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='total_referrals',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='UserReferrals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('my_referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usersdetails')),
            ],
        ),
    ]
