# Generated by Django 4.2.14 on 2024-08-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersdetails_can_take_from_pool_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='is_add_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='QgdRuWbEJ1p2,B89', max_length=30),
        ),
    ]
