# Generated by Django 4.2.14 on 2024-08-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_usersdetails_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='anRw,BE6CkdKmvY7', max_length=30),
        ),
    ]
