# Generated by Django 4.2.14 on 2024-08-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_usersdetails_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='last_update',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='AA7546SDs6JUvygo', max_length=30),
        ),
    ]
