# Generated by Django 4.2.14 on 2024-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_usersdetails_last_update_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImproveTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_name', models.CharField(choices=[('Instagram', 'instagram'), ('Telegram', 'telegram'), ('YouTube', 'youtube')], max_length=20)),
                ('task_name', models.CharField(max_length=100)),
                ('task_code', models.CharField(max_length=100)),
                ('prize_coin', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('is_active', models.BooleanField()),
                ('task_link', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='MV,aHwqMQPhMzspB', max_length=30),
        ),
    ]
