# Generated by Django 4.2.14 on 2024-08-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_improvetask_alter_usersdetails_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='unp_token',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('telegram', 'Telegram'), ('instagram', 'Instagram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(default='ndo,0YOsrXYiC4oT', max_length=30),
        ),
    ]
