# Generated by Django 4.2.14 on 2024-08-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_usersdetails_unp_token_alter_improvetask_social_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Twitter', 'Twitter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='can_take_from_pool',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='coin_pool',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='usersdetails',
            name='referral_code',
            field=models.CharField(max_length=30),
        ),
    ]
