# Generated by Django 4.2.14 on 2024-08-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_improvetask_social_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='is_reach_10_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='is_reach_20_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersdetails',
            name='is_reach_30_ref',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram'), ('YouTube', 'YouTube')], max_length=20),
        ),
    ]
