# Generated by Django 4.2.14 on 2024-08-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_usersdetails_is_reach_10_ref_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube')], max_length=20),
        ),
        migrations.CreateModel(
            name='UserWantDoTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('for_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.improvetask')),
                ('for_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usersdetails')),
            ],
        ),
    ]
