# Generated by Django 4.2.14 on 2024-08-20 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_improvetask_channel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('Twitter', 'Twitter')], max_length=20),
        ),
    ]
