# Generated by Django 4.2.14 on 2024-08-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillDailyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_filled', models.BooleanField(default=False)),
                ('fill_time', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram'), ('Instagram', 'Instagram')], max_length=20),
        ),
    ]
