# Generated by Django 4.2.14 on 2024-08-21 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube')], max_length=20),
        ),
    ]
