# Generated by Django 4.2.14 on 2024-08-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram')], max_length=20),
        ),
    ]
