# Generated by Django 4.2.14 on 2024-08-24 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillDailyPoolTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_time', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='FillDailyPool',
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='channel_username',
            field=models.CharField(blank=True, help_text='like : @unipoly', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='is_need_check_channel',
            field=models.BooleanField(default=False, help_text='if enable this option you need to fill below field'),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Telegram', 'Telegram')], max_length=20),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='task_code',
            field=models.CharField(help_text='take prize with this code', max_length=100),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='task_name',
            field=models.CharField(max_length=100, verbose_name='task description'),
        ),
    ]
