# Generated by Django 4.2.14 on 2024-08-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_improvetask_is_need_enter_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Twitter', 'Twitter'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='task_name',
            field=models.TextField(max_length=100, verbose_name='task description'),
        ),
    ]
