# Generated by Django 4.2.14 on 2024-08-24 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_improvetask_social_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvetask',
            name='time_left',
            field=models.DateTimeField(blank=True, help_text='Set time left (Enable is_need_enter_code)', null=True),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Telegram', 'Telegram'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Twitter', 'Twitter')], max_length=20),
        ),
    ]
