# Generated by Django 4.2.14 on 2024-08-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_improvetask_time_left_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Twitter', 'Twitter')], max_length=20),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='task_code',
            field=models.CharField(blank=True, help_text='Take prize with this code (Enable is_need_enter_code)', max_length=100, null=True),
        ),
    ]
