# Generated by Django 4.2.14 on 2024-08-24 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_alter_improvetask_social_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userwantdotask',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userwantdotask',
            name='is_need_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('YouTube', 'YouTube')], max_length=20),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='task_name',
            field=models.TextField(verbose_name='task description'),
        ),
        migrations.AlterField(
            model_name='userwantdotask',
            name='start_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
