# Generated by Django 4.2.14 on 2024-08-24 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_userwantdotask_code_userwantdotask_is_need_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvetask',
            name='task_title',
            field=models.CharField(default=231231, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=20),
        ),
    ]
