# Generated by Django 4.2.14 on 2024-08-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_improvetask_task_title_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='task_pool',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Instagram', 'Instagram'), ('Telegram', 'Telegram'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=20),
        ),
    ]
