# Generated by Django 4.2.14 on 2024-08-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_usersdetails_task_pool_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='improvetask',
            name='prize_tap',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('Twitter', 'Twitter'), ('YouTube', 'YouTube'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=20),
        ),
    ]
