# Generated by Django 4.2.14 on 2024-08-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_improvetask_prize_tap_alter_improvetask_social_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdetails',
            name='cheat_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='improvetask',
            name='social_name',
            field=models.CharField(choices=[('YouTube', 'YouTube'), ('Twitter', 'Twitter'), ('Instagram', 'Instagram'), ('Telegram', 'Telegram')], max_length=20),
        ),
    ]
